/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

/**
 * Converts a File object to a base64 encoded string for the Gemini API.
 * @param {File} file The file to convert.
 * @returns {Promise<{mimeType: string, data: string}>} A promise that resolves with the generative part.
 */
export function fileToGenerativePart(file: File): Promise<{mimeType: string, data: string}> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      if (!result || !result.startsWith('data:')) {
          reject(new Error('Invalid file format or failed to read file as data URL.'));
          return;
      }
      
      const parts = result.split(',');
      if (parts.length < 2 || !parts[1]) {
          reject(new Error('Could not extract base64 data from file. The file might be empty or corrupt.'));
          return;
      }

      const base64Data = parts[1];
      resolve({
        mimeType: file.type,
        data: base64Data
      });
    };
    reader.onerror = () => reject(new Error(`Error reading file: ${reader.error?.message || 'Unknown error'}`));
    reader.readAsDataURL(file);
  });
}

/**
 * Combines the hardcoded base prompt, JSON rules, and CSV data into a
 * single comprehensive prompt for the Gemini model. This function is now
 * synchronous as the knowledge base is bundled.
 * @returns {string} The full prompt text.
 */
export function getPrompt(): string {
    const basePrompt = `You are a professional trading analyst specializing in short-term (intraday and daily) technical and fundamental analysis. Your task is to analyze an image of a candlestick chart.

**Part 1: Technical Analysis (Visual)**
- Based on the expert knowledge provided in the JSON and CSV data below, identify the primary candlestick pattern in the provided image.
- Suggest 2-3 additional technical indicators (e.g., RSI, MACD, Moving Averages) that could confirm the identified pattern's signal. Briefly explain why each would be useful for this pattern.

**Part 2: Fundamental Analysis (News)**
- Identify the stock/crypto symbol from the image or from the user-provided context.
- Use Google Search to find relevant, breaking news from the last 12-24 hours from verified, reputable financial news outlets.
- Analyze the sentiment of the news (positive, negative, neutral).

**Part 3: Synthesize and Output for Short-Term Trading**
- Combine your visual technical analysis and fundamental news analysis to provide a comprehensive trading recommendation specifically for **short-term (intraday to 3-day) trading strategies**.
- The news sentiment should adjust the profit probability and trading advice for this short-term context.
- The \`takeProfitLevel\`, \`stopLossLevel\`, and \`takeProfitTimeframe\` (e.g., '15-60 minutes', '1-4 hours') must be appropriate for day trading or swing trading over a few days.
- Provide your complete analysis in a single, raw JSON object. **Do not wrap it in markdown backticks or add any other text before or after the JSON.**

The JSON object must have the following structure. For fields requiring translation, provide an object with "en" and "bg" keys.

- patternName: {"en": "English Pattern Name", "bg": "Bulgarian Pattern Name"}
- signal: {"en": "Buy" | "Sell" | "Neutral", "bg": "Купува" | "Продава" | "Неутрален"}
- profitProbability: A success rate percentage range (e.g., "55-72%"). This is a string and does not need translation.
- confirmationIndicators: {"en": "English indicator advice", "bg": "Bulgarian indicator advice"}
- takeProfitLevel: Suggested take profit price (string, no translation).
- stopLossLevel: Suggested stop loss price (string, no translation).
- takeProfitTimeframe: Suggested timeframe (e.g., "15-60 minutes") (string, no translation).
- tradingAdvice: {"en": "English trading advice", "bg": "Bulgarian trading advice"}
- summary: {"en": "English summary", "bg": "Bulgarian summary"}

Analyze the provided chart image and return ONLY the raw JSON object string. Ensure the specified fields are translated into both English and Bulgarian as shown in the structure above.`;

    const jsonRules = `{
      "title": "Gemini Rule Cards for Candlestick Patterns",
      "version": "1.0",
      "generated_at": "2025-10-27 09:52:33 UTC",
      "rules": [
        { "pattern": "Hammer", "category": "Reversal", "type": "Single-candle bullish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "support", "weight": 0.06 } }, "confirmation": "Next candle closes above hammer high.", "entry_rule": "Buy on confirmation close/break above high.", "stop_loss": "Below wick low.", "take_profit": "Next resistance.", "notes": "Best with volume spike/HTF support.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Shooting Star", "category": "Reversal", "type": "Single-candle bearish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "resistance", "weight": 0.06 } }, "confirmation": "Next candle closes below shooting star low.", "entry_rule": "Sell on confirmation close/break below low.", "stop_loss": "Above wick high.", "take_profit": "Next support.", "notes": "RSI>70 confluence helps.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Hanging Man", "category": "Reversal", "type": "Single-candle bearish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "resistance", "weight": 0.06 } }, "confirmation": "Close below low confirms.", "entry_rule": "Sell on break/close below low.", "stop_loss": "Above high.", "take_profit": "Nearest support.", "notes": "Needs resistance confluence.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Doji (Standard)", "category": "Indecision", "type": "Single-candle indecision", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Follow next candle direction.", "entry_rule": "Trade only with confirmation & S/R.", "stop_loss": "Beyond doji wick.", "take_profit": "Nearest S/R.", "notes": "Variants: Dragonfly/Gravestone/Long-Legged.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Dragonfly Doji", "category": "Reversal/Indecision", "type": "Single-candle bullish reversal (often)", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "support", "weight": 0.06 } }, "confirmation": "Bullish follow-through above high.", "entry_rule": "Buy on confirmation.", "stop_loss": "Below wick low.", "take_profit": "Next resistance.", "notes": "Volume spike strengthens.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Gravestone Doji", "category": "Reversal/Indecision", "type": "Single-candle bearish reversal (often)", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "resistance", "weight": 0.06 } }, "confirmation": "Bearish follow-through below low.", "entry_rule": "Sell on confirmation.", "stop_loss": "Above wick high.", "take_profit": "Next support.", "notes": "Overbought/divergence helps.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Marubozu (Shaven)", "category": "Continuation/Reversal", "type": "Single-candle momentum", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Continuation biased unless at exhaustion.", "entry_rule": "With-trend entries on minor pullbacks.", "stop_loss": "Opposite side structure.", "take_profit": "Trend targets.", "notes": "Watch for blow-off risk.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Spinning Top", "category": "Indecision", "type": "Single-candle indecision", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Trade only with break/confirmation.", "entry_rule": "Break in trend direction.", "stop_loss": "Opposite side of candle.", "take_profit": "Nearest S/R.", "notes": "Lower weight in chop.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Bullish Engulfing", "category": "Reversal", "type": "Two-candle bullish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "support", "weight": 0.06 } }, "confirmation": "Close above engulfing high.", "entry_rule": "Buy on confirmation; scale on pullbacks.", "stop_loss": "Below engulfing low.", "take_profit": "Next resistance.", "notes": "Multi-candle engulf stronger.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Bearish Engulfing", "category": "Reversal", "type": "Two-candle bearish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "resistance", "weight": 0.06 } }, "confirmation": "Close below engulfing low.", "entry_rule": "Sell on confirmation.", "stop_loss": "Above engulfing high.", "take_profit": "Next support.", "notes": "Volume expansion helps.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Harami (Bullish)", "category": "Reversal", "type": "Two-candle bullish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "support", "weight": 0.06 } }, "confirmation": "Break/close above mother bar high.", "entry_rule": "Buy breakout of mother-bar high.", "stop_loss": "Below harami low.", "take_profit": "First resistance.", "notes": "Best with support confluence.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Harami (Bearish)", "category": "Reversal", "type": "Two-candle bearish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "resistance", "weight": 0.06 } }, "confirmation": "Break/close below mother bar low.", "entry_rule": "Sell breakout of mother-bar low.", "stop_loss": "Above harami high.", "take_profit": "First support.", "notes": "Best with resistance confluence.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Piercing Line", "category": "Reversal", "type": "Two-candle bullish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "support", "weight": 0.06 } }, "confirmation": "Further upside closes above prior high.", "entry_rule": "Buy on confirmation.", "stop_loss": "Below second low.", "take_profit": "Nearest resistance.", "notes": "Best at support.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Dark Cloud Cover", "category": "Reversal", "type": "Two-candle bearish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "resistance", "weight": 0.06 } }, "confirmation": "Close below second low confirms.", "entry_rule": "Sell on confirmation.", "stop_loss": "Above second high.", "take_profit": "Nearest support.", "notes": "Best at resistance.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Inside Bar", "category": "Continuation/Breakout", "type": "Two-candle consolidation", "base_probability": 0.6, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Breakout of mother-bar range.", "entry_rule": "Stop orders beyond range.", "stop_loss": "Opposite side of mother bar.", "take_profit": "ATR/structure.", "notes": "False-break setup powerful.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Morning Star", "category": "Reversal", "type": "Three-candle bullish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "support", "weight": 0.06 } }, "confirmation": "Continuation above third high.", "entry_rule": "Buy on third close/break.", "stop_loss": "Below pattern low.", "take_profit": "Next resistance.", "notes": "Doji variant stronger.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Evening Star", "category": "Reversal", "type": "Three-candle bearish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "resistance", "weight": 0.06 } }, "confirmation": "Continuation below third low.", "entry_rule": "Sell on third close/break.", "stop_loss": "Above pattern high.", "take_profit": "Next support.", "notes": "Doji variant stronger.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Three White Soldiers", "category": "Reversal/Continuation", "type": "Three-candle bullish", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "support", "weight": 0.06 } }, "confirmation": "Follow-through higher.", "entry_rule": "Pullback entry to mid bodies.", "stop_loss": "Below pattern low.", "take_profit": "Next resistance.", "notes": "Beware exhaustion.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Three Black Crows", "category": "Reversal/Continuation", "type": "Three-candle bearish", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "resistance", "weight": 0.06 } }, "confirmation": "Follow-through lower.", "entry_rule": "Sell pullbacks to mid bodies.", "stop_loss": "Above pattern high.", "take_profit": "Next support.", "notes": "Avoid shorting into support.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Rising Three Methods", "category": "Continuation", "type": "Five-candle bullish continuation", "base_probability": 0.6, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Breakout continuation.", "entry_rule": "Buy breakout of pattern high.", "stop_loss": "Below consolidation low.", "take_profit": "Trend targets.", "notes": "Opposite: Falling Three Methods.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Falling Three Methods", "category": "Continuation", "type": "Five-candle bearish continuation", "base_probability": 0.6, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Breakdown continuation.", "entry_rule": "Sell breakdown of pattern low.", "stop_loss": "Above consolidation high.", "take_profit": "Trend targets.", "notes": "Opposite: Rising Three Methods.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Mat Hold (Bullish)", "category": "Continuation", "type": "Five-candle bullish continuation", "base_probability": 0.6, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Sustained continuation.", "entry_rule": "Buy on break/retest.", "stop_loss": "Below pause low.", "take_profit": "Trend targets.", "notes": "Volume contraction→expansion ideal.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Tweezer Top/Bottom", "category": "Reversal", "type": "Two-candle reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Break opposite to prior move.", "entry_rule": "Enter on confirming break.", "stop_loss": "Beyond tweezers extreme.", "take_profit": "Nearest S/R.", "notes": "Best at HTF levels.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Kicker", "category": "Reversal", "type": "Two-candle sharp reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Gap holds; trend flips.", "entry_rule": "Enter on kicker close.", "stop_loss": "Opposite side of gap.", "take_profit": "Gap fill/structure.", "notes": "Needs strong volume.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Tasuki Gap (Upside)", "category": "Continuation", "type": "Three-candle bullish continuation", "base_probability": 0.6, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Gap remains unfilled.", "entry_rule": "Buy continuation.", "stop_loss": "Below gap low.", "take_profit": "Trend targets.", "notes": "Prefer rising volume.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Tasuki Gap (Downside)", "category": "Continuation", "type": "Three-candle bearish continuation", "base_probability": 0.6, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Gap remains unfilled.", "entry_rule": "Sell continuation.", "stop_loss": "Above gap high.", "take_profit": "Trend targets.", "notes": "Prefer rising volume.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Abandoned Baby (Bullish)", "category": "Reversal", "type": "Three-candle bullish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "support", "weight": 0.06 } }, "confirmation": "Strong bullish follow-through.", "entry_rule": "Buy on gap/confirm.", "stop_loss": "Below doji low.", "take_profit": "Resistance targets.", "notes": "Rare; check liquidity.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Abandoned Baby (Bearish)", "category": "Reversal", "type": "Three-candle bearish reversal", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "resistance", "weight": 0.06 } }, "confirmation": "Strong bearish follow-through.", "entry_rule": "Sell on gap/confirm.", "stop_loss": "Above doji high.", "take_profit": "Support targets.", "notes": "Rare; check liquidity.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Outside Bar", "category": "Reversal/Continuation", "type": "Two-candle expansion", "base_probability": 0.58, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Break continuation in close direction.", "entry_rule": "Enter on break in close direction.", "stop_loss": "Opposite side of outside bar.", "take_profit": "ATR/structure.", "notes": "Beware news spikes.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Popgun", "category": "Breakout", "type": "Two-candle contraction/expansion", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Break in outside-bar direction.", "entry_rule": "Enter on break of outside bar.", "stop_loss": "Opposite side of outside bar.", "take_profit": "ATR/structure.", "notes": "Avoid into nearby S/R.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Head and Shoulders", "category": "Complex Formation", "type": "Multi-swing bearish reversal", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Close below neckline (retest ideal).", "entry_rule": "Sell on break/retest.", "stop_loss": "Above RS high.", "take_profit": "Measured move (head→neckline).", "notes": "Inverse variant is bullish.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Inverse Head and Shoulders", "category": "Complex Formation", "type": "Multi-swing bullish reversal", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Close above neckline (retest ideal).", "entry_rule": "Buy on break/retest.", "stop_loss": "Below RS low.", "take_profit": "Measured move.", "notes": "Volume confirmation helps.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Double Top", "category": "Complex Formation", "type": "Bearish reversal", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": 0.06, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Neckline break confirms.", "entry_rule": "Sell on break/retest.", "stop_loss": "Above peaks.", "take_profit": "Measured height.", "notes": "Avoid early shorts before break.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Double Bottom", "category": "Complex Formation", "type": "Bullish reversal", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": 0.06, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Neckline break confirms.", "entry_rule": "Buy on break/retest.", "stop_loss": "Below lows.", "take_profit": "Measured height.", "notes": "Volume on breakout helps.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Ascending Triangle (Bullish)", "category": "Complex Formation", "type": "Continuation", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Break and close above resistance.", "entry_rule": "Buy breakout/retest.", "stop_loss": "Below last HL.", "take_profit": "Height projection.", "notes": "Time at resistance increases odds.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Symmetrical Triangle", "category": "Complex Formation", "type": "Continuation (either way)", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Break with volume in trend direction.", "entry_rule": "Trade in trend direction.", "stop_loss": "Beyond opposite TL.", "take_profit": "Base width projection.", "notes": "Beware apex fakeouts.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Bull Flag", "category": "Complex Formation", "type": "Continuation", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Breakout above flag.", "entry_rule": "Buy breakout; add on retest.", "stop_loss": "Below flag low.", "take_profit": "Flagpole projection.", "notes": "Avoid wide/slow flags.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Bear Flag", "category": "Complex Formation", "type": "Continuation", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Breakdown below flag.", "entry_rule": "Sell breakdown; add on retest.", "stop_loss": "Above flag high.", "take_profit": "Flagpole projection.", "notes": "Mind HTF support.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" },
        { "pattern": "Pennant", "category": "Complex Formation", "type": "Continuation", "base_probability": 0.52, "boosts": { "trend": { "strong_up": 0.08, "strong_down": 0.08, "range": 0.0 }, "rsi": { "overbought": -0.02, "oversold": -0.02, "neutral": 0.0 }, "volume": { "high": 0.06, "low": -0.04 }, "location": { "preferred": "trend-continuation-zone", "weight": 0.06 } }, "confirmation": "Break in pole direction.", "entry_rule": "Enter on break; tight stops.", "stop_loss": "Opposite side of pennant.", "take_profit": "Pole projection.", "notes": "Short duration preferred.", "scoring": "score = base + trend_mod + rsi_mod + volume_mod + (0.06 if preferred location)" }
      ]
    }`;

    const csvData = `Front,Back,Extra
"Hammer — define, context, confirmation?",Type: Single-candle bullish reversal<br>Category: Reversal<br>Context: After downtrend at support; long lower wick (≥2× body).<br>Appearance: Small body near top; Long lower wick; Tiny/no upper wick<br>Confirmation: Next candle closes above hammer high.<br>Entry: Buy on confirmation close/break above high.<br>Stop: Below wick low.<br>TP: Next resistance.<br>Notes: Best with volume spike/HTF support.<br>Base Prob: 0.58,"Related: Inverted Hammer, Hanging Man | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Shooting Star — define, context, confirmation?",Type: Single-candle bearish reversal<br>Category: Reversal<br>Context: After uptrend at resistance; long upper wick (≥2× body).<br>Appearance: Small body near bottom; Long upper wick; Tiny/no lower wick<br>Confirmation: Next candle closes below shooting star low.<br>Entry: Sell on confirmation close/break below low.<br>Stop: Above wick high.<br>TP: Next support.<br>Notes: RSI>70 confluence helps.<br>Base Prob: 0.58,"Related: Gravestone Doji, Bearish Pin Bar | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Hanging Man — define, context, confirmation?",Type: Single-candle bearish reversal<br>Category: Reversal<br>Context: Top of uptrend; same anatomy as hammer but bearish context.<br>Appearance: Small body near top; Long lower wick<br>Confirmation: Close below low confirms.<br>Entry: Sell on break/close below low.<br>Stop: Above high.<br>TP: Nearest support.<br>Notes: Needs resistance confluence.<br>Base Prob: 0.58,"Related: Hammer, Shooting Star | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Doji (Standard) — define, context, confirmation?",Type: Single-candle indecision<br>Category: Indecision<br>Context: Any trend; open≈close.<br>Appearance: Small/zero body; wicks may exist<br>Confirmation: Follow next candle direction.<br>Entry: Trade only with confirmation & S/R.<br>Stop: Beyond doji wick.<br>TP: Nearest S/R.<br>Notes: Variants: Dragonfly/Gravestone/Long-Legged.<br>Base Prob: 0.52,"Related: Dragonfly Doji, Gravestone Doji | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Dragonfly Doji — define, context, confirmation?",Type: Single-candle bullish reversal (often)<br>Category: Reversal/Indecision<br>Context: After downtrend; open≈close≈high; long lower wick.<br>Appearance: Long lower wick; No/short upper wick<br>Confirmation: Bullish follow-through above high.<br>Entry: Buy on confirmation.<br>Stop: Below wick low.<br>TP: Next resistance.<br>Notes: Volume spike strengthens.<br>Base Prob: 0.58,"Related: Hammer, Doji | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Gravestone Doji — define, context, confirmation?",Type: Single-candle bearish reversal (often)<br>Category: Reversal/Indecision<br>Context: After uptrend; open≈close≈low; long upper wick.<br>Appearance: Long upper wick; No/short lower wick<br>Confirmation: Bearish follow-through below low.<br>Entry: Sell on confirmation.<br>Stop: Above wick high.<br>TP: Next support.<br>Notes: Overbought/divergence helps.<br>Base Prob: 0.58,"Related: Shooting Star, Doji | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Marubozu (Shaven) — define, context, confirmation?",Type: Single-candle momentum<br>Category: Continuation/Reversal<br>Context: Full body with minimal/no wicks.<br>Appearance: Full body (open at/near low; close at/near high for bullish)<br>Confirmation: Continuation biased unless at exhaustion.<br>Entry: With-trend entries on minor pullbacks.<br>Stop: Opposite side structure.<br>TP: Trend targets.<br>Notes: Watch for blow-off risk.<br>Base Prob: 0.58,"Related: Belt Hold | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Spinning Top — define, context, confirmation?",Type: Single-candle indecision<br>Category: Indecision<br>Context: Small body; wicks both sides.<br>Appearance: Small body; upper & lower wicks<br>Confirmation: Trade only with break/confirmation.<br>Entry: Break in trend direction.<br>Stop: Opposite side of candle.<br>TP: Nearest S/R.<br>Notes: Lower weight in chop.<br>Base Prob: 0.52,"Related: High Wave, Doji | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Bullish Engulfing — define, context, confirmation?",Type: Two-candle bullish reversal<br>Category: Reversal<br>Context: After downtrend at support.<br>Appearance: Small bearish then larger bullish engulfing body<br>Confirmation: Close above engulfing high.<br>Entry: Buy on confirmation; scale on pullbacks.<br>Stop: Below engulfing low.<br>TP: Next resistance.<br>Notes: Multi-candle engulf stronger.<br>Base Prob: 0.58,"Related: Bearish Engulfing, Three White Soldiers | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Bearish Engulfing — define, context, confirmation?",Type: Two-candle bearish reversal<br>Category: Reversal<br>Context: After uptrend at resistance.<br>Appearance: Small bullish then larger bearish engulfing body<br>Confirmation: Close below engulfing low.<br>Entry: Sell on confirmation.<br>Stop: Above engulfing high.<br>TP: Next support.<br>Notes: Volume expansion helps.<br>Base Prob: 0.58,"Related: Bullish Engulfing, Three Black Crows | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Harami (Bullish) — define, context, confirmation?",Type: Two-candle bullish reversal<br>Category: Reversal<br>Context: Downtrend; small bullish inside large bearish body.<br>Appearance: Inside small body<br>Confirmation: Break/close above mother bar high.<br>Entry: Buy breakout of mother-bar high.<br>Stop: Below harami low.<br>TP: First resistance.<br>Notes: Best with support confluence.<br>Base Prob: 0.58,"Related: Harami (Bearish), Inside Bar | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Harami (Bearish) — define, context, confirmation?",Type: Two-candle bearish reversal<br>Category: Reversal<br>Context: Uptrend; small bearish inside large bullish body.<br>Appearance: Inside small body<br>Confirmation: Break/close below mother bar low.<br>Entry: Sell breakout of mother-bar low.<br>Stop: Above harami high.<br>TP: First support.<br>Notes: Best with resistance confluence.<br>Base Prob: 0.58,"Related: Harami (Bullish), Inside Bar | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Piercing Line — define, context, confirmation?",Type: Two-candle bullish reversal<br>Category: Reversal<br>Context: Downtrend; gap down then bullish closes >50% into prior body.<br>Appearance: Bearish then bullish closing > midpoint<br>Confirmation: Further upside closes above prior high.<br>Entry: Buy on confirmation.<br>Stop: Below second low.<br>TP: Nearest resistance.<br>Notes: Best at support.<br>Base Prob: 0.58,"Related: Dark Cloud Cover, Bullish Engulfing | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Dark Cloud Cover — define, context, confirmation?",Type: Two-candle bearish reversal<br>Category: Reversal<br>Context: Uptrend; gap up then bearish closes >50% into prior body.<br>Appearance: Bullish then bearish closing > midpoint down<br>Confirmation: Close below second low confirms.<br>Entry: Sell on confirmation.<br>Stop: Above second high.<br>TP: Nearest support.<br>Notes: Best at resistance.<br>Base Prob: 0.58,"Related: Piercing Line, Bearish Engulfing | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Inside Bar — define, context, confirmation?",Type: Two-candle consolidation<br>Category: Continuation/Breakout<br>Context: Second candle inside prior range.<br>Appearance: Full inside range<br>Confirmation: Breakout of mother-bar range.<br>Entry: Stop orders beyond range.<br>Stop: Opposite side of mother bar.<br>TP: ATR/structure.<br>Notes: False-break setup powerful.<br>Base Prob: 0.6,"Related: Harami, Popgun | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Morning Star — define, context, confirmation?",Type: Three-candle bullish reversal<br>Category: Reversal<br>Context: Bottom of downtrend.<br>Appearance: Long bearish; small indecision; strong bullish > mid of first<br>Confirmation: Continuation above third high.<br>Entry: Buy on third close/break.<br>Stop: Below pattern low.<br>TP: Next resistance.<br>Notes: Doji variant stronger.<br>Base Prob: 0.58,"Related: Evening Star, Three Inside Up | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Evening Star — define, context, confirmation?",Type: Three-candle bearish reversal<br>Category: Reversal<br>Context: Top of uptrend.<br>Appearance: Long bullish; small indecision; strong bearish < mid of first<br>Confirmation: Continuation below third low.<br>Entry: Sell on third close/break.<br>Stop: Above pattern high.<br>TP: Next support.<br>Notes: Doji variant stronger.<br>Base Prob: 0.58,"Related: Morning Star, Three Inside Down | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Three White Soldiers — define, context, confirmation?",Type: Three-candle bullish<br>Category: Reversal/Continuation<br>Context: After downtrend or consolidation.<br>Appearance: 3 consecutive bullish closes near highs<br>Confirmation: Follow-through higher.<br>Entry: Pullback entry to mid bodies.<br>Stop: Below pattern low.<br>TP: Next resistance.<br>Notes: Beware exhaustion.<br>Base Prob: 0.58,"Related: Three Black Crows | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Three Black Crows — define, context, confirmation?",Type: Three-candle bearish<br>Category: Reversal/Continuation<br>Context: After uptrend or range.<br>Appearance: 3 consecutive bearish closes near lows<br>Confirmation: Follow-through lower.<br>Entry: Sell pullbacks to mid bodies.<br>Stop: Above pattern high.<br>TP: Next support.<br>Notes: Avoid shorting into support.<br>Base Prob: 0.58,"Related: Three White Soldiers | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Rising Three Methods — define, context, confirmation?",Type: Five-candle bullish continuation<br>Category: Continuation<br>Context: Uptrend; pause then continue.<br>Appearance: Long bullish; 3 small bearish inside; strong bullish breakout<br>Confirmation: Breakout continuation.<br>Entry: Buy breakout of pattern high.<br>Stop: Below consolidation low.<br>TP: Trend targets.<br>Notes: Opposite: Falling Three Methods.<br>Base Prob: 0.6,"Related: Falling Three Methods, Mat Hold | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Falling Three Methods — define, context, confirmation?",Type: Five-candle bearish continuation<br>Category: Continuation<br>Context: Downtrend; pause then continue.<br>Appearance: Long bearish; 3 small bullish inside; strong bearish breakdown<br>Confirmation: Breakdown continuation.<br>Entry: Sell breakdown of pattern low.<br>Stop: Above consolidation high.<br>TP: Trend targets.<br>Notes: Opposite: Rising Three Methods.<br>Base Prob: 0.6,"Related: Rising Three Methods, Mat Hold | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Mat Hold (Bullish) — define, context, confirmation?",Type: Five-candle bullish continuation<br>Category: Continuation<br>Context: Strong uptrend; shallow drift then break.<br>Appearance: Large bullish; 3 small drifting down/sideways; bullish break<br>Confirmation: Sustained continuation.<br>Entry: Buy on break/retest.<br>Stop: Below pause low.<br>TP: Trend targets.<br>Notes: Volume contraction→expansion ideal.<br>Base Prob: 0.6,"Related: Rising Three Methods | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Tweezer Top/Bottom — define, context, confirmation?",Type: Two-candle reversal<br>Category: Reversal<br>Context: Equal highs (top) / equal lows (bottom).<br>Appearance: Matching extremes across two candles<br>Confirmation: Break opposite to prior move.<br>Entry: Enter on confirming break.<br>Stop: Beyond tweezers extreme.<br>TP: Nearest S/R.<br>Notes: Best at HTF levels.<br>Base Prob: 0.58,"Related: Double Top/Bottom | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Kicker — define, context, confirmation?",Type: Two-candle sharp reversal<br>Category: Reversal<br>Context: Gap open in opposite direction; minimal overlap.<br>Appearance: Gap with dominant opposite candle<br>Confirmation: Gap holds; trend flips.<br>Entry: Enter on kicker close.<br>Stop: Opposite side of gap.<br>TP: Gap fill/structure.<br>Notes: Needs strong volume.<br>Base Prob: 0.58,"Related: Breakaway, Island Reversal | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Tasuki Gap (Upside) — define, context, confirmation?",Type: Three-candle bullish continuation<br>Category: Continuation<br>Context: Uptrend gap continues; small down candle does not fill gap.<br>Appearance: Gap up; down candle; next continues up<br>Confirmation: Gap remains unfilled.<br>Entry: Buy continuation.<br>Stop: Below gap low.<br>TP: Trend targets.<br>Notes: Prefer rising volume.<br>Base Prob: 0.6,"Related: Separating Lines (Bullish) | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Tasuki Gap (Downside) — define, context, confirmation?",Type: Three-candle bearish continuation<br>Category: Continuation<br>Context: Downtrend gap continues; small up candle does not fill gap.<br>Appearance: Gap down; up candle; next continues down<br>Confirmation: Gap remains unfilled.<br>Entry: Sell continuation.<br>Stop: Above gap high.<br>TP: Trend targets.<br>Notes: Prefer rising volume.<br>Base Prob: 0.6,"Related: Separating Lines (Bearish) | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Abandoned Baby (Bullish) — define, context, confirmation?",Type: Three-candle bullish reversal<br>Category: Reversal<br>Context: Downtrend; gap-down doji isolated; gap-up reversal.<br>Appearance: Doji with gaps both sides<br>Confirmation: Strong bullish follow-through.<br>Entry: Buy on gap/confirm.<br>Stop: Below doji low.<br>TP: Resistance targets.<br>Notes: Rare; check liquidity.<br>Base Prob: 0.58,"Related: Morning Star, Island Reversal | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Abandoned Baby (Bearish) — define, context, confirmation?",Type: Three-candle bearish reversal<br>Category: Reversal<br>Context: Uptrend; gap-up doji isolated; gap-down reversal.<br>Appearance: Doji with gaps both sides<br>Confirmation: Strong bearish follow-through.<br>Entry: Sell on gap/confirm.<br>Stop: Above doji high.<br>TP: Support targets.<br>Notes: Rare; check liquidity.<br>Base Prob: 0.58,"Related: Evening Star, Island Reversal | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Outside Bar — define, context, confirmation?",Type: Two-candle expansion<br>Category: Reversal/Continuation<br>Context: Second bar engulfs prior high and low.<br>Appearance: Range expansion bar<br>Confirmation: Break continuation in close direction.<br>Entry: Enter on break in close direction.<br>Stop: Opposite side of outside bar.<br>TP: ATR/structure.<br>Notes: Beware news spikes.<br>Base Prob: 0.58,"Related: Engulfing, Popgun | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Popgun — define, context, confirmation?",Type: Two-candle contraction/expansion<br>Category: Breakout<br>Context: Inside bar then outside bar.<br>Appearance: Inside→Outside sequence<br>Confirmation: Break in outside-bar direction.<br>Entry: Enter on break of outside bar.<br>Stop: Opposite side of outside bar.<br>TP: ATR/structure.<br>Notes: Avoid into nearby S/R.<br>Base Prob: 0.52,"Related: Inside Bar, Outside Bar | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Head and Shoulders — define, context, confirmation?",Type: Multi-swing bearish reversal<br>Category: Complex Formation<br>Context: Top formation; neckline break.<br>Appearance: LS-Head-RS + neckline<br>Confirmation: Close below neckline (retest ideal).<br>Entry: Sell on break/retest.<br>Stop: Above RS high.<br>TP: Measured move (head→neckline).<br>Notes: Inverse variant is bullish.<br>Base Prob: 0.52,"Related: Inverse Head and Shoulders, Double Top | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Inverse Head and Shoulders — define, context, confirmation?",Type: Multi-swing bullish reversal<br>Category: Complex Formation<br>Context: Bottom formation; neckline break.<br>Appearance: L-Head-R + neckline<br>Confirmation: Close above neckline (retest ideal).<br>Entry: Buy on break/retest.<br>Stop: Below RS low.<br>TP: Measured move.<br>Notes: Volume confirmation helps.<br>Base Prob: 0.52,"Related: Head and Shoulders, Double Bottom | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Double Top — define, context, confirmation?",Type: Bearish reversal<br>Category: Complex Formation<br>Context: Two peaks at resistance; neckline below.<br>Appearance: Two highs ~ equal; neckline trough<br>Confirmation: Neckline break confirms.<br>Entry: Sell on break/retest.<br>Stop: Above peaks.<br>TP: Measured height.<br>Notes: Avoid early shorts before break.<br>Base Prob: 0.52,"Related: Double Bottom, Tweezer Top | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Double Bottom — define, context, confirmation?",Type: Bullish reversal<br>Category: Complex Formation<br>Context: Two lows at support; neckline above.<br>Appearance: Two lows ~ equal; neckline peak<br>Confirmation: Neckline break confirms.<br>Entry: Buy on break/retest.<br>Stop: Below lows.<br>TP: Measured height.<br>Notes: Volume on breakout helps.<br>Base Prob: 0.52,"Related: Double Top, Tweezer Bottom | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Ascending Triangle (Bullish) — define, context, confirmation?",Type: Continuation<br>Category: Complex Formation<br>Context: Flat resistance with rising lows.<br>Appearance: Horizontal top + rising TL<br>Confirmation: Break and close above resistance.<br>Entry: Buy breakout/retest.<br>Stop: Below last HL.<br>TP: Height projection.<br>Notes: Time at resistance increases odds.<br>Base Prob: 0.52,"Related: Symmetrical Triangle, Bull Flag | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Symmetrical Triangle — define, context, confirmation?",Type: Continuation (either way)<br>Category: Complex Formation<br>Context: Converging highs/lows.<br>Appearance: Two converging TLs<br>Confirmation: Break with volume in trend direction.<br>Entry: Trade in trend direction.<br>Stop: Beyond opposite TL.<br>TP: Base width projection.<br>Notes: Beware apex fakeouts.<br>Base Prob: 0.52,"Related: Pennant, Ascending/Descending Triangle | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Bull Flag — define, context, confirmation?",Type: Continuation<br>Category: Complex Formation<br>Context: Sharp impulse up then downward channel.<br>Appearance: Flagpole + downward flag<br>Confirmation: Breakout above flag.<br>Entry: Buy breakout; add on retest.<br>Stop: Below flag low.<br>TP: Flagpole projection.<br>Notes: Avoid wide/slow flags.<br>Base Prob: 0.52,"Related: Bear Flag, Pennant | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Bear Flag — define, context, confirmation?",Type: Continuation<br>Category: Complex Formation<br>Context: Sharp impulse down then upward channel.<br>Appearance: Flagpole + upward flag<br>Confirmation: Breakdown below flag.<br>Entry: Sell breakdown; add on retest.<br>Stop: Above flag high.<br>TP: Flagpole projection.<br>Notes: Mind HTF support.<br>Base Prob: 0.52,"Related: Bull Flag, Pennant | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"
"Pennant — define, context, confirmation?",Type: Continuation<br>Category: Complex Formation<br>Context: Small symmetrical triangle after strong pole.<br>Appearance: Short converging consolidation<br>Confirmation: Break in pole direction.<br>Entry: Enter on break; tight stops.<br>Stop: Opposite side of pennant.<br>TP: Pole projection.<br>Notes: Short duration preferred.<br>Base Prob: 0.52,"Related: Flag, Symmetrical Triangle | Sources: Merged from uploaded PDFs (WR Trading, KohanFX, Classical)"`;

    // Combine them into a single, structured prompt
    const fullPrompt = `
${basePrompt}

Here is the expert knowledge base you must use for your analysis. Prioritize this information over your general knowledge.

--- START OF JSON KNOWLEDGE BASE ---
${jsonRules}
--- END OF JSON KNOWLEDGE BASE ---

--- START OF CSV KNOWLEDGE BASE (Flashcard format) ---
${csvData}
--- END OF CSV KNOWLEDGE BASE ---

Now, analyze the provided chart image based on these rules and return ONLY the raw JSON object string as requested in the instructions above.
`;

    return fullPrompt.trim();
}